spring:
  application:
    name: dollar-review
  datasource:
    url: ${rds.host}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
jwt:
  key: ${jwt.secret.key}
aws:
  access:
    key: ${access.key.id}
  secret:
    key: ${aws.secret.key}

review:
  bucket:
    name: ${review.bucket.name}

server:
  port: 8085

loadbalancer:
  product: ${load.product}
  order: ${load.order}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    customCssUrl: /swagger-ui/theme-newspaper.css
  packages-to-scan: org.example.dollarreview.review.controller
