spring:
  application:
    name: dollar-order
  datasource:
    url: ${rds.host}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: ${redis.host}
      port: 6379
jwt:
  key: ${jwt.secret.key}
  
kakao:
  api:
    admin-key: ${kakao.api.admin-key}

order:
  public-base-url: ${ORDER_PUBLIC_BASE_URL:http://localhost:8080}
    
server:
  port: 8084
aws:
  access:
    key: ${access.key.id}
  secret:
    key: ${aws.secret.key}

loadbalancer:
  user: ${load.user}
  product: ${load.product}
